UPSTREAM: <carry>: Add replaces in go.mod and generate go.sum
Reported to USPTREAM: https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/issues/896

Can be dropped if upstream adds this replace to go.mod:

k8s.io/endpointslice => k8s.io/endpointslice v0.29.4
k8s.io/dynamic-resource-allocation => k8s.io/dynamic-resource-allocation v0.29.4

Commit fixes verify-deps check which was failing with:

 go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/endpointslice@v0.0.0: invalid version: unknown revision v0.0.0
go: google.golang.org/genproto/googleapis/rpc@v0.0.0-20230822172742-b8732ec3820d: missing go.sum entry for go.mod file; to add it:
	go mod download google.golang.org/genproto/googleapis/rpc
ERROR: go list -mod=readonly -m all failed with the message listed above.
Cachito used in ART builds will fail to resolve dependencies offline.
Typically, a pinned version is missing in go.mod, e.g.:
    replace k8s.io/foo => k8s.io/foo v0.26.0